-- ECS MVP Schema (lean brand + department model)
-- Adjust database/schema names and role/warehouse to your environment.

-- Example setup (optional):
-- CREATE DATABASE IF NOT EXISTS ECS_DB;
-- CREATE SCHEMA IF NOT EXISTS ECS_DB.ECS_MVP;
-- USE SCHEMA ECS_DB.ECS_MVP;

CREATE OR REPLACE TABLE ROLES (
  ROLE_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1,
  ROLE_KEY VARCHAR(50) NOT NULL,
  ROLE_NAME VARCHAR(100) NOT NULL,
  IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (ROLE_ID)
);

CREATE OR REPLACE TABLE BRANDS (
  BRAND_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1,
  BRAND_CODE VARCHAR(50) NOT NULL,
  BRAND_NAME VARCHAR(200) NOT NULL,
  IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_TZ,
  PRIMARY KEY (BRAND_ID)
);

CREATE OR REPLACE TABLE DEPARTMENTS (
  DEPARTMENT_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1,
  DEPARTMENT_CODE VARCHAR(50) NOT NULL,
  DEPARTMENT_NAME VARCHAR(200) NOT NULL,
  IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_TZ,
  PRIMARY KEY (DEPARTMENT_ID)
);

CREATE OR REPLACE TABLE USERS (
  USER_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1,
  EMAIL VARCHAR(320) NOT NULL,
  DISPLAY_NAME VARCHAR(200) NOT NULL,
  BRAND_ID NUMBER(38,0),
  DEPARTMENT_ID NUMBER(38,0),
  IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_TZ,
  PRIMARY KEY (USER_ID)
);

CREATE OR REPLACE TABLE USER_ROLES (
  USER_ID NUMBER(38,0) NOT NULL,
  ROLE_ID NUMBER(38,0) NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (USER_ID, ROLE_ID)
);

CREATE OR REPLACE TABLE SOPS (
  SOP_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1,
  DOCUMENT_NO VARCHAR(50) NOT NULL,
  DOCUMENT_TYPE VARCHAR(30) NOT NULL,
  TITLE VARCHAR(300) NOT NULL,
  BRAND_ID NUMBER(38,0),
  DEPARTMENT_ID NUMBER(38,0) NOT NULL,
  COMPLIANCE_AREA VARCHAR(100) NOT NULL,
  OWNER_USER_ID NUMBER(38,0),
  VERSION_NO VARCHAR(30) NOT NULL,
  STATUS VARCHAR(30) NOT NULL,
  FILE_NAME VARCHAR(255),
  FILE_URL VARCHAR(1000),
  FILE_SIZE NUMBER(18,0),
  MIME_TYPE VARCHAR(100),
  SUBMITTED_BY NUMBER(38,0),
  SUBMITTED_AT TIMESTAMP_TZ,
  APPROVED_BY NUMBER(38,0),
  APPROVED_AT TIMESTAMP_TZ,
  APPROVAL_REMARKS VARCHAR(2000),
  ACTIVE_FROM DATE,
  NEXT_REVIEW_DATE DATE,
  REMARKS VARCHAR(2000),
  CREATED_BY NUMBER(38,0) NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY NUMBER(38,0),
  UPDATED_AT TIMESTAMP_TZ,
  PRIMARY KEY (SOP_ID)
);

CREATE OR REPLACE TABLE SOP_ASSIGNMENTS (
  ASSIGNMENT_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1,
  SOP_ID NUMBER(38,0) NOT NULL,
  BRAND_ID NUMBER(38,0) NOT NULL,
  DEPARTMENT_ID NUMBER(38,0) NOT NULL,
  OWNER_USER_ID NUMBER(38,0),
  STATUS VARCHAR(30) NOT NULL,
  TARGET_DATE DATE,
  COMPLETED_AT TIMESTAMP_TZ,
  VERIFIED_BY NUMBER(38,0),
  VERIFIED_AT TIMESTAMP_TZ,
  REMARKS VARCHAR(2000),
  CREATED_BY NUMBER(38,0) NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY NUMBER(38,0),
  UPDATED_AT TIMESTAMP_TZ,
  PRIMARY KEY (ASSIGNMENT_ID)
);

CREATE OR REPLACE TABLE CHECKLIST_TEMPLATES (
  TEMPLATE_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1,
  TEMPLATE_NAME VARCHAR(200) NOT NULL,
  COMPLIANCE_AREA VARCHAR(100) NOT NULL,
  IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  CREATED_BY NUMBER(38,0) NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY NUMBER(38,0),
  UPDATED_AT TIMESTAMP_TZ,
  PRIMARY KEY (TEMPLATE_ID)
);

CREATE OR REPLACE TABLE CHECKLIST_ITEMS (
  ITEM_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1,
  TEMPLATE_ID NUMBER(38,0) NOT NULL,
  SECTION_NAME VARCHAR(200),
  ITEM_TEXT VARCHAR(1000) NOT NULL,
  WEIGHT NUMBER(10,2) NOT NULL DEFAULT 1,
  SORT_ORDER NUMBER(38,0) NOT NULL DEFAULT 0,
  IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (ITEM_ID)
);

CREATE OR REPLACE TABLE AUDITS (
  AUDIT_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1,
  TEMPLATE_ID NUMBER(38,0) NOT NULL,
  BRAND_ID NUMBER(38,0) NOT NULL,
  DEPARTMENT_ID NUMBER(38,0) NOT NULL,
  COMPLIANCE_AREA VARCHAR(100) NOT NULL,
  STATUS VARCHAR(30) NOT NULL,
  PERFORMED_BY NUMBER(38,0) NOT NULL,
  STARTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  COMPLETED_AT TIMESTAMP_TZ,
  SCORE_PERCENT NUMBER(10,2),
  REMARKS VARCHAR(2000),
  PRIMARY KEY (AUDIT_ID)
);

CREATE OR REPLACE TABLE AUDIT_RESPONSES (
  RESPONSE_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1,
  AUDIT_ID NUMBER(38,0) NOT NULL,
  ITEM_ID NUMBER(38,0) NOT NULL,
  RESULT VARCHAR(30) NOT NULL,
  COMMENTS VARCHAR(2000),
  PRIMARY KEY (RESPONSE_ID)
);

CREATE OR REPLACE TABLE CORRECTIVE_ACTIONS (
  ACTION_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1,
  SOURCE_TYPE VARCHAR(30) NOT NULL,
  SOURCE_ID NUMBER(38,0),
  TITLE VARCHAR(300) NOT NULL,
  DESCRIPTION VARCHAR(2000),
  BRAND_ID NUMBER(38,0),
  DEPARTMENT_ID NUMBER(38,0),
  ASSIGNED_TO NUMBER(38,0) NOT NULL,
  SEVERITY VARCHAR(30) NOT NULL,
  STATUS VARCHAR(30) NOT NULL,
  DUE_DATE DATE NOT NULL,
  SUBMITTED_BY NUMBER(38,0),
  SUBMITTED_AT TIMESTAMP_TZ,
  VERIFIED_BY NUMBER(38,0),
  VERIFIED_AT TIMESTAMP_TZ,
  CLOSED_AT TIMESTAMP_TZ,
  REMARKS VARCHAR(2000),
  CREATED_BY NUMBER(38,0) NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY NUMBER(38,0),
  UPDATED_AT TIMESTAMP_TZ,
  PRIMARY KEY (ACTION_ID)
);

CREATE OR REPLACE TABLE EVIDENCE_FILES (
  EVIDENCE_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1,
  ENTITY_TYPE VARCHAR(50) NOT NULL,
  ENTITY_ID NUMBER(38,0) NOT NULL,
  FILE_NAME VARCHAR(255) NOT NULL,
  FILE_URL VARCHAR(1000) NOT NULL,
  FILE_SIZE NUMBER(18,0),
  MIME_TYPE VARCHAR(100),
  REMARKS VARCHAR(2000),
  CREATED_BY NUMBER(38,0) NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (EVIDENCE_ID)
);

CREATE OR REPLACE TABLE KPI_DEFINITIONS (
  KPI_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1,
  KPI_NAME VARCHAR(200) NOT NULL,
  BRAND_ID NUMBER(38,0),
  DEPARTMENT_ID NUMBER(38,0),
  TARGET_VALUE NUMBER(18,4),
  TARGET_DIRECTION VARCHAR(5) NOT NULL DEFAULT '>=',
  OWNER_USER_ID NUMBER(38,0),
  IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  CREATED_BY NUMBER(38,0) NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (KPI_ID)
);

CREATE OR REPLACE TABLE KPI_RESULTS (
  KPI_RESULT_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1,
  KPI_ID NUMBER(38,0) NOT NULL,
  REPORTING_MONTH DATE NOT NULL,
  ACTUAL_VALUE NUMBER(18,4) NOT NULL,
  STATUS VARCHAR(10),
  COMMENTS VARCHAR(2000),
  CREATED_BY NUMBER(38,0) NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (KPI_RESULT_ID)
);

CREATE OR REPLACE TABLE AUDIT_LOG (
  LOG_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1,
  ENTITY_TYPE VARCHAR(50) NOT NULL,
  ENTITY_ID NUMBER(38,0) NOT NULL,
  ACTION VARCHAR(100) NOT NULL,
  CHANGED_BY NUMBER(38,0) NOT NULL,
  DETAILS VARIANT,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (LOG_ID)
);

ALTER TABLE ROLES ADD CONSTRAINT UQ_ROLES_ROLE_KEY UNIQUE (ROLE_KEY);
ALTER TABLE BRANDS ADD CONSTRAINT UQ_BRANDS_BRAND_CODE UNIQUE (BRAND_CODE);
ALTER TABLE DEPARTMENTS ADD CONSTRAINT UQ_DEPARTMENTS_DEPARTMENT_CODE UNIQUE (DEPARTMENT_CODE);
ALTER TABLE USERS ADD CONSTRAINT UQ_USERS_EMAIL UNIQUE (EMAIL);
ALTER TABLE SOPS ADD CONSTRAINT UQ_SOPS_DOCUMENT_NO UNIQUE (DOCUMENT_NO);
ALTER TABLE SOP_ASSIGNMENTS ADD CONSTRAINT UQ_SOP_ASSIGNMENTS UNIQUE (SOP_ID, BRAND_ID, DEPARTMENT_ID);
