USE DATABASE SWISH_DOCUMENTS;
USE SCHEMA ECS_MVP;

CREATE OR REPLACE VIEW VW_SOP_STATUS_SUMMARY AS
SELECT
  STATUS,
  COUNT(*) AS SOP_COUNT
FROM SOPS
GROUP BY STATUS;

CREATE OR REPLACE VIEW VW_SOP_STATUS_BY_SCOPE AS
SELECT
  CASE
    WHEN s.DEPARTMENT_ID IS NOT NULL AND s.LOCATION_ID IS NOT NULL THEN 'BRAND_DEPARTMENT_LOCATION'
    WHEN s.DEPARTMENT_ID IS NOT NULL THEN 'BRAND_DEPARTMENT'
    WHEN s.LOCATION_ID IS NOT NULL THEN 'BRAND_LOCATION'
    ELSE 'BRAND'
  END AS SCOPE_LEVEL,
  s.BRAND_ID,
  b.BRAND_CODE,
  b.BRAND_NAME,
  s.DEPARTMENT_ID,
  d.DEPARTMENT_CODE,
  d.DEPARTMENT_NAME,
  s.LOCATION_ID,
  l.LOCATION_CODE,
  l.LOCATION_NAME,
  s.STATUS,
  COUNT(*) AS SOP_COUNT
FROM SOPS s
LEFT JOIN BRANDS b ON b.BRAND_ID = s.BRAND_ID
LEFT JOIN DEPARTMENTS d ON d.DEPARTMENT_ID = s.DEPARTMENT_ID
LEFT JOIN LOCATIONS l ON l.LOCATION_ID = s.LOCATION_ID
GROUP BY
  CASE
    WHEN s.DEPARTMENT_ID IS NOT NULL AND s.LOCATION_ID IS NOT NULL THEN 'BRAND_DEPARTMENT_LOCATION'
    WHEN s.DEPARTMENT_ID IS NOT NULL THEN 'BRAND_DEPARTMENT'
    WHEN s.LOCATION_ID IS NOT NULL THEN 'BRAND_LOCATION'
    ELSE 'BRAND'
  END,
  s.BRAND_ID,
  b.BRAND_CODE,
  b.BRAND_NAME,
  s.DEPARTMENT_ID,
  d.DEPARTMENT_CODE,
  d.DEPARTMENT_NAME,
  s.LOCATION_ID,
  l.LOCATION_CODE,
  l.LOCATION_NAME,
  s.STATUS;

CREATE OR REPLACE VIEW VW_SOP_IMPLEMENTATION_SUMMARY AS
SELECT
  COUNT(*) AS TOTAL_ASSIGNMENTS,
  SUM(IFF(STATUS IN ('Implemented', 'Verified'), 1, 0)) AS IMPLEMENTED_OR_VERIFIED,
  SUM(IFF(STATUS = 'Verified', 1, 0)) AS VERIFIED_COUNT,
  ROUND(100.0 * SUM(IFF(STATUS IN ('Implemented', 'Verified'), 1, 0)) / NULLIF(COUNT(*), 0), 2) AS IMPLEMENTED_PERCENT,
  ROUND(100.0 * SUM(IFF(STATUS = 'Verified', 1, 0)) / NULLIF(COUNT(*), 0), 2) AS VERIFIED_PERCENT
FROM SOP_ASSIGNMENTS;

CREATE OR REPLACE VIEW VW_SOP_IMPLEMENTATION_BY_SCOPE AS
SELECT
  CASE
    WHEN sa.DEPARTMENT_ID IS NOT NULL AND sa.LOCATION_ID IS NOT NULL THEN 'BRAND_DEPARTMENT_LOCATION'
    WHEN sa.DEPARTMENT_ID IS NOT NULL THEN 'BRAND_DEPARTMENT'
    WHEN sa.LOCATION_ID IS NOT NULL THEN 'BRAND_LOCATION'
    ELSE 'BRAND'
  END AS SCOPE_LEVEL,
  sa.BRAND_ID,
  b.BRAND_CODE,
  b.BRAND_NAME,
  sa.DEPARTMENT_ID,
  d.DEPARTMENT_CODE,
  d.DEPARTMENT_NAME,
  sa.LOCATION_ID,
  l.LOCATION_CODE,
  l.LOCATION_NAME,
  sa.STATUS,
  COUNT(*) AS ASSIGNMENT_COUNT
FROM SOP_ASSIGNMENTS sa
LEFT JOIN BRANDS b ON b.BRAND_ID = sa.BRAND_ID
LEFT JOIN DEPARTMENTS d ON d.DEPARTMENT_ID = sa.DEPARTMENT_ID
LEFT JOIN LOCATIONS l ON l.LOCATION_ID = sa.LOCATION_ID
GROUP BY
  CASE
    WHEN sa.DEPARTMENT_ID IS NOT NULL AND sa.LOCATION_ID IS NOT NULL THEN 'BRAND_DEPARTMENT_LOCATION'
    WHEN sa.DEPARTMENT_ID IS NOT NULL THEN 'BRAND_DEPARTMENT'
    WHEN sa.LOCATION_ID IS NOT NULL THEN 'BRAND_LOCATION'
    ELSE 'BRAND'
  END,
  sa.BRAND_ID,
  b.BRAND_CODE,
  b.BRAND_NAME,
  sa.DEPARTMENT_ID,
  d.DEPARTMENT_CODE,
  d.DEPARTMENT_NAME,
  sa.LOCATION_ID,
  l.LOCATION_CODE,
  l.LOCATION_NAME,
  sa.STATUS;

CREATE OR REPLACE VIEW VW_CORRECTIVE_ACTION_SUMMARY AS
SELECT
  STATUS,
  COUNT(*) AS ACTION_COUNT,
  SUM(IFF(SEVERITY IN ('High', 'Critical'), 1, 0)) AS HIGH_SEVERITY_COUNT
FROM CORRECTIVE_ACTIONS
GROUP BY STATUS;

CREATE OR REPLACE VIEW VW_CORRECTIVE_ACTION_BY_SCOPE AS
SELECT
  CASE
    WHEN ca.DEPARTMENT_ID IS NOT NULL AND ca.LOCATION_ID IS NOT NULL THEN 'BRAND_DEPARTMENT_LOCATION'
    WHEN ca.DEPARTMENT_ID IS NOT NULL THEN 'BRAND_DEPARTMENT'
    WHEN ca.LOCATION_ID IS NOT NULL THEN 'BRAND_LOCATION'
    ELSE 'BRAND'
  END AS SCOPE_LEVEL,
  ca.BRAND_ID,
  b.BRAND_CODE,
  b.BRAND_NAME,
  ca.DEPARTMENT_ID,
  d.DEPARTMENT_CODE,
  d.DEPARTMENT_NAME,
  ca.LOCATION_ID,
  l.LOCATION_CODE,
  l.LOCATION_NAME,
  ca.STATUS,
  ca.SEVERITY,
  COUNT(*) AS ACTION_COUNT
FROM CORRECTIVE_ACTIONS ca
LEFT JOIN BRANDS b ON b.BRAND_ID = ca.BRAND_ID
LEFT JOIN DEPARTMENTS d ON d.DEPARTMENT_ID = ca.DEPARTMENT_ID
LEFT JOIN LOCATIONS l ON l.LOCATION_ID = ca.LOCATION_ID
GROUP BY
  CASE
    WHEN ca.DEPARTMENT_ID IS NOT NULL AND ca.LOCATION_ID IS NOT NULL THEN 'BRAND_DEPARTMENT_LOCATION'
    WHEN ca.DEPARTMENT_ID IS NOT NULL THEN 'BRAND_DEPARTMENT'
    WHEN ca.LOCATION_ID IS NOT NULL THEN 'BRAND_LOCATION'
    ELSE 'BRAND'
  END,
  ca.BRAND_ID,
  b.BRAND_CODE,
  b.BRAND_NAME,
  ca.DEPARTMENT_ID,
  d.DEPARTMENT_CODE,
  d.DEPARTMENT_NAME,
  ca.LOCATION_ID,
  l.LOCATION_CODE,
  l.LOCATION_NAME,
  ca.STATUS,
  ca.SEVERITY;

CREATE OR REPLACE VIEW VW_OVERDUE_ACTIONS AS
SELECT
  ca.ACTION_ID,
  ca.SOURCE_TYPE,
  ca.SOURCE_ID,
  ca.TITLE,
  ca.DESCRIPTION,
  CASE
    WHEN ca.DEPARTMENT_ID IS NOT NULL AND ca.LOCATION_ID IS NOT NULL THEN 'BRAND_DEPARTMENT_LOCATION'
    WHEN ca.DEPARTMENT_ID IS NOT NULL THEN 'BRAND_DEPARTMENT'
    WHEN ca.LOCATION_ID IS NOT NULL THEN 'BRAND_LOCATION'
    ELSE 'BRAND'
  END AS SCOPE_LEVEL,
  ca.BRAND_ID,
  b.BRAND_CODE,
  b.BRAND_NAME,
  ca.DEPARTMENT_ID,
  d.DEPARTMENT_CODE,
  d.DEPARTMENT_NAME,
  ca.LOCATION_ID,
  l.LOCATION_CODE,
  l.LOCATION_NAME,
  ca.ASSIGNED_TO,
  u.DISPLAY_NAME AS ASSIGNED_TO_NAME,
  ca.SEVERITY,
  ca.STATUS,
  ca.DUE_DATE,
  DATEDIFF('DAY', ca.DUE_DATE, CURRENT_DATE()) AS DAYS_OVERDUE,
  ca.REMARKS,
  ca.CREATED_AT,
  ca.UPDATED_AT
FROM CORRECTIVE_ACTIONS ca
LEFT JOIN BRANDS b ON b.BRAND_ID = ca.BRAND_ID
LEFT JOIN DEPARTMENTS d ON d.DEPARTMENT_ID = ca.DEPARTMENT_ID
LEFT JOIN LOCATIONS l ON l.LOCATION_ID = ca.LOCATION_ID
LEFT JOIN USERS u ON u.USER_ID = ca.ASSIGNED_TO
WHERE ca.DUE_DATE < CURRENT_DATE()
  AND ca.STATUS NOT IN ('Verified', 'Closed');

CREATE OR REPLACE VIEW VW_KPI_STATUS_DETAIL AS
SELECT
  r.KPI_RESULT_ID,
  r.KPI_ID,
  d.KPI_NAME,
  CASE
    WHEN COALESCE(r.DEPARTMENT_ID, d.DEPARTMENT_ID) IS NOT NULL AND COALESCE(r.LOCATION_ID, d.LOCATION_ID) IS NOT NULL THEN 'BRAND_DEPARTMENT_LOCATION'
    WHEN COALESCE(r.DEPARTMENT_ID, d.DEPARTMENT_ID) IS NOT NULL THEN 'BRAND_DEPARTMENT'
    WHEN COALESCE(r.LOCATION_ID, d.LOCATION_ID) IS NOT NULL THEN 'BRAND_LOCATION'
    ELSE 'BRAND'
  END AS SCOPE_LEVEL,
  COALESCE(r.BRAND_ID, d.BRAND_ID) AS BRAND_ID,
  b.BRAND_CODE,
  b.BRAND_NAME,
  COALESCE(r.DEPARTMENT_ID, d.DEPARTMENT_ID) AS DEPARTMENT_ID,
  dept.DEPARTMENT_CODE,
  dept.DEPARTMENT_NAME,
  COALESCE(r.LOCATION_ID, d.LOCATION_ID) AS LOCATION_ID,
  l.LOCATION_CODE,
  l.LOCATION_NAME,
  r.REPORTING_MONTH,
  d.TARGET_VALUE,
  d.TARGET_DIRECTION,
  r.ACTUAL_VALUE,
  COALESCE(
    r.STATUS,
    CASE
      WHEN d.TARGET_VALUE IS NULL THEN NULL
      WHEN d.TARGET_DIRECTION = '>=' AND r.ACTUAL_VALUE >= d.TARGET_VALUE THEN 'Green'
      WHEN d.TARGET_DIRECTION = '>=' AND r.ACTUAL_VALUE >= d.TARGET_VALUE * 0.95 THEN 'Amber'
      WHEN d.TARGET_DIRECTION = '<=' AND r.ACTUAL_VALUE <= d.TARGET_VALUE THEN 'Green'
      WHEN d.TARGET_DIRECTION = '<=' AND r.ACTUAL_VALUE <= d.TARGET_VALUE * 1.05 THEN 'Amber'
      ELSE 'Red'
    END
  ) AS FINAL_STATUS,
  r.COMMENTS,
  r.CREATED_AT
FROM KPI_RESULTS r
JOIN KPI_DEFINITIONS d ON d.KPI_ID = r.KPI_ID
LEFT JOIN BRANDS b ON b.BRAND_ID = COALESCE(r.BRAND_ID, d.BRAND_ID)
LEFT JOIN DEPARTMENTS dept ON dept.DEPARTMENT_ID = COALESCE(r.DEPARTMENT_ID, d.DEPARTMENT_ID)
LEFT JOIN LOCATIONS l ON l.LOCATION_ID = COALESCE(r.LOCATION_ID, d.LOCATION_ID);

CREATE OR REPLACE VIEW VW_KPI_STATUS_SUMMARY AS
SELECT
  REPORTING_MONTH,
  FINAL_STATUS AS STATUS,
  COUNT(*) AS KPI_COUNT
FROM VW_KPI_STATUS_DETAIL
GROUP BY REPORTING_MONTH, FINAL_STATUS;

CREATE OR REPLACE VIEW VW_AUDIT_SCORE_SUMMARY AS
SELECT
  DATE_TRUNC('MONTH', COALESCE(COMPLETED_AT, STARTED_AT))::DATE AS AUDIT_MONTH,
  COUNT(*) AS AUDIT_COUNT,
  ROUND(AVG(SCORE_PERCENT), 2) AS AVG_SCORE_PERCENT
FROM AUDITS
WHERE STATUS = 'Completed'
GROUP BY DATE_TRUNC('MONTH', COALESCE(COMPLETED_AT, STARTED_AT))::DATE;

CREATE OR REPLACE VIEW VW_AUDIT_SCORE_BY_SCOPE AS
SELECT
  CASE
    WHEN a.DEPARTMENT_ID IS NOT NULL AND a.LOCATION_ID IS NOT NULL THEN 'BRAND_DEPARTMENT_LOCATION'
    WHEN a.DEPARTMENT_ID IS NOT NULL THEN 'BRAND_DEPARTMENT'
    WHEN a.LOCATION_ID IS NOT NULL THEN 'BRAND_LOCATION'
    ELSE 'BRAND'
  END AS SCOPE_LEVEL,
  a.BRAND_ID,
  b.BRAND_CODE,
  b.BRAND_NAME,
  a.DEPARTMENT_ID,
  d.DEPARTMENT_CODE,
  d.DEPARTMENT_NAME,
  a.LOCATION_ID,
  l.LOCATION_CODE,
  l.LOCATION_NAME,
  DATE_TRUNC('MONTH', COALESCE(a.COMPLETED_AT, a.STARTED_AT))::DATE AS AUDIT_MONTH,
  COUNT(*) AS AUDIT_COUNT,
  ROUND(AVG(a.SCORE_PERCENT), 2) AS AVG_SCORE_PERCENT
FROM AUDITS a
LEFT JOIN BRANDS b ON b.BRAND_ID = a.BRAND_ID
LEFT JOIN DEPARTMENTS d ON d.DEPARTMENT_ID = a.DEPARTMENT_ID
LEFT JOIN LOCATIONS l ON l.LOCATION_ID = a.LOCATION_ID
WHERE a.STATUS = 'Completed'
GROUP BY
  CASE
    WHEN a.DEPARTMENT_ID IS NOT NULL AND a.LOCATION_ID IS NOT NULL THEN 'BRAND_DEPARTMENT_LOCATION'
    WHEN a.DEPARTMENT_ID IS NOT NULL THEN 'BRAND_DEPARTMENT'
    WHEN a.LOCATION_ID IS NOT NULL THEN 'BRAND_LOCATION'
    ELSE 'BRAND'
  END,
  a.BRAND_ID,
  b.BRAND_CODE,
  b.BRAND_NAME,
  a.DEPARTMENT_ID,
  d.DEPARTMENT_CODE,
  d.DEPARTMENT_NAME,
  a.LOCATION_ID,
  l.LOCATION_CODE,
  l.LOCATION_NAME,
  DATE_TRUNC('MONTH', COALESCE(a.COMPLETED_AT, a.STARTED_AT))::DATE;

CREATE OR REPLACE VIEW VW_DASHBOARD_SUMMARY AS
WITH sop AS (
  SELECT
    COUNT(*) AS TOTAL_SOPS,
    SUM(IFF(STATUS = 'Approved', 1, 0)) AS APPROVED_SOPS,
    SUM(IFF(STATUS = 'Submitted', 1, 0)) AS PENDING_SOPS,
    SUM(IFF(STATUS = 'Active', 1, 0)) AS ACTIVE_SOPS
  FROM SOPS
),
impl AS (
  SELECT
    ROUND(100.0 * SUM(IFF(STATUS IN ('Implemented', 'Verified'), 1, 0)) / NULLIF(COUNT(*), 0), 2) AS SOP_IMPLEMENTATION_PERCENT
  FROM SOP_ASSIGNMENTS
),
ca AS (
  SELECT
    SUM(IFF(STATUS IN ('Open', 'In Progress', 'Submitted'), 1, 0)) AS OPEN_CORRECTIVE_ACTIONS,
    SUM(IFF(DUE_DATE < CURRENT_DATE() AND STATUS NOT IN ('Verified', 'Closed'), 1, 0)) AS OVERDUE_CORRECTIVE_ACTIONS
  FROM CORRECTIVE_ACTIONS
),
kpi AS (
  SELECT
    SUM(IFF(FINAL_STATUS = 'Green', 1, 0)) AS GREEN_KPIS,
    SUM(IFF(FINAL_STATUS = 'Amber', 1, 0)) AS AMBER_KPIS,
    SUM(IFF(FINAL_STATUS = 'Red', 1, 0)) AS RED_KPIS
  FROM VW_KPI_STATUS_DETAIL
  WHERE REPORTING_MONTH = (
    SELECT MAX(REPORTING_MONTH)
    FROM KPI_RESULTS
  )
),
audit AS (
  SELECT
    ROUND(AVG(SCORE_PERCENT), 2) AS FOOD_SAFETY_AUDIT_SCORE
  FROM AUDITS
  WHERE STATUS = 'Completed'
    AND COMPLIANCE_AREA = 'Food Safety Compliance'
)
SELECT
  COALESCE(sop.TOTAL_SOPS, 0) AS TOTAL_SOPS,
  COALESCE(sop.APPROVED_SOPS, 0) AS APPROVED_SOPS,
  COALESCE(sop.PENDING_SOPS, 0) AS PENDING_SOPS,
  COALESCE(sop.ACTIVE_SOPS, 0) AS ACTIVE_SOPS,
  COALESCE(impl.SOP_IMPLEMENTATION_PERCENT, 0) AS SOP_IMPLEMENTATION_PERCENT,
  COALESCE(ca.OPEN_CORRECTIVE_ACTIONS, 0) AS OPEN_CORRECTIVE_ACTIONS,
  COALESCE(ca.OVERDUE_CORRECTIVE_ACTIONS, 0) AS OVERDUE_CORRECTIVE_ACTIONS,
  COALESCE(kpi.GREEN_KPIS, 0) AS GREEN_KPIS,
  COALESCE(kpi.AMBER_KPIS, 0) AS AMBER_KPIS,
  COALESCE(kpi.RED_KPIS, 0) AS RED_KPIS,
  COALESCE(audit.FOOD_SAFETY_AUDIT_SCORE, 0) AS FOOD_SAFETY_AUDIT_SCORE
FROM sop
CROSS JOIN impl
CROSS JOIN ca
CROSS JOIN kpi
CROSS JOIN audit;
