USE DATABASE SWISH_DOCUMENTS;
USE SCHEMA ECS_MVP;

MERGE INTO ROLES target
USING (
  SELECT 'ADMIN' AS ROLE_KEY, 'Admin' AS ROLE_NAME
  UNION ALL SELECT 'BUSINESS_EXCELLENCE', 'Business Excellence'
  UNION ALL SELECT 'DEPARTMENT_OWNER', 'Department Owner'
  UNION ALL SELECT 'AUDITOR', 'Auditor'
  UNION ALL SELECT 'EXECUTIVE_VIEWER', 'Executive Viewer'
) source
ON target.ROLE_KEY = source.ROLE_KEY
WHEN MATCHED THEN UPDATE SET target.ROLE_NAME = source.ROLE_NAME
WHEN NOT MATCHED THEN INSERT (ROLE_KEY, ROLE_NAME) VALUES (source.ROLE_KEY, source.ROLE_NAME);

MERGE INTO BRANDS target
USING (
  SELECT 'BBT' AS BRAND_CODE, 'BBT' AS BRAND_NAME
  UNION ALL SELECT 'CHP', 'CHILLY PEPPER'
  UNION ALL SELECT 'FM', 'FOREVERMORE'
  UNION ALL SELECT 'BUR', 'JUST C'
  UNION ALL SELECT 'MM', 'MISHMASH'
  UNION ALL SELECT 'PAT', 'PATTIE PATTIE'
  UNION ALL SELECT 'SS', 'SHAKIR'
  UNION ALL SELECT 'SLC', 'SLICE'
  UNION ALL SELECT 'TBL', 'TABEL'
  UNION ALL SELECT 'YP', 'YELO PIZZA'
) source
ON target.BRAND_CODE = source.BRAND_CODE
WHEN MATCHED THEN UPDATE SET target.BRAND_NAME = source.BRAND_NAME
WHEN NOT MATCHED THEN INSERT (BRAND_CODE, BRAND_NAME) VALUES (source.BRAND_CODE, source.BRAND_NAME);
