USE DATABASE SWISH_DOCUMENTS;
USE SCHEMA ECS_MVP;

MERGE INTO DEPARTMENTS target
USING (
  SELECT 'ADMINISTRATION' AS DEPARTMENT_CODE, 'ADMINISTRATION' AS DEPARTMENT_NAME
  UNION ALL SELECT 'BAKERY', 'BAKERY'
  UNION ALL SELECT 'BUSINESS_DEVELOPMENT', 'BUSINESS_DEVELOPMENT'
  UNION ALL SELECT 'BUSINESS_EXCELLENCE', 'BUSINESS_EXCELLENCE'
  UNION ALL SELECT 'CEO', 'CEO'
  UNION ALL SELECT 'COST_CONTROLLER', 'COST_CONTROLLER'
  UNION ALL SELECT 'CUSTOMER_CARE', 'CUSTOMER_CARE'
  UNION ALL SELECT 'FINANCE', 'FINANCE'
  UNION ALL SELECT 'GM', 'GM'
  UNION ALL SELECT 'GROWTH', 'GROWTH'
  UNION ALL SELECT 'HR', 'HR'
  UNION ALL SELECT 'IT', 'IT'
  UNION ALL SELECT 'MARKETING', 'MARKETING'
  UNION ALL SELECT 'OPERATIONS', 'OPERATIONS'
  UNION ALL SELECT 'OPEX', 'OPEX'
  UNION ALL SELECT 'PERFORMANCE_ANALYTICS', 'PERFORMANCE_ANALYTICS'
  UNION ALL SELECT 'PROCUREMENT', 'PROCUREMENT'
  UNION ALL SELECT 'PRODUCTION', 'PRODUCTION'
  UNION ALL SELECT 'RND', 'RND'
  UNION ALL SELECT 'TECHNICAL', 'TECHNICAL'
  UNION ALL SELECT 'TRAINING', 'TRAINING'
  UNION ALL SELECT 'WAREHOUSE_LOGISTICS', 'WAREHOUSE_LOGISTICS'
) source
ON target.DEPARTMENT_CODE = source.DEPARTMENT_CODE
WHEN MATCHED THEN UPDATE SET target.DEPARTMENT_NAME = source.DEPARTMENT_NAME
WHEN NOT MATCHED THEN INSERT (DEPARTMENT_CODE, DEPARTMENT_NAME) VALUES (source.DEPARTMENT_CODE, source.DEPARTMENT_NAME);
