USE DATABASE SWISH_DOCUMENTS;
USE SCHEMA ECS_MVP;

MERGE INTO LOCATIONS target
USING (
  SELECT 'DHY' AS LOCATION_CODE, 'ABDULLAH AL SALEM (DAHIYA)' AS LOCATION_NAME
  UNION ALL SELECT 'ADL', 'ADALIYA'
  UNION ALL SELECT 'AHM', 'AHMADI'
  UNION ALL SELECT 'AND', 'ANDALOUS'
  UNION ALL SELECT 'ARD', 'ARDHIYA'
  UNION ALL SELECT 'BYN', 'BAYAN'
  UNION ALL SELECT 'BNQ', 'BNEID AL QAR'
  UNION ALL SELECT 'AGL', 'EGAILA'
  UNION ALL SELECT 'FHL', 'FAHAHEEL'
  UNION ALL SELECT 'HWL', 'HAWALLY'
  UNION ALL SELECT 'ISH', 'ISHBILIYA'
  UNION ALL SELECT 'JAD', 'JABER AL AHMED'
  UNION ALL SELECT 'JBR', 'JABRIYA'
  UNION ALL SELECT 'JHR', 'JAHRA'
  UNION ALL SELECT 'JLB', 'JLEEB AL SHUYOUKH'
  UNION ALL SELECT 'KFN', 'KAIFAN'
  UNION ALL SELECT 'KHR', 'KHAIRAN'
  UNION ALL SELECT 'KTN', 'KHAITHAN'
  UNION ALL SELECT 'KWT', 'KUWAIT CITY'
  UNION ALL SELECT 'MHB', 'MAHBOULA'
  UNION ALL SELECT 'MID', 'MAIDAN HAWALLY'
  UNION ALL SELECT 'MNF', 'MANGAF'
  UNION ALL SELECT 'MIS', 'MISHREF'
  UNION ALL SELECT 'QDS', 'QADSIYA'
  UNION ALL SELECT 'QTB', 'QORTUBA'
  UNION ALL SELECT 'QRN', 'QURAIN'
  UNION ALL SELECT 'RAI', 'RAI'
  UNION ALL SELECT 'SAD', 'SAAD AL ABDULLAH'
  UNION ALL SELECT 'SBA', 'SABAH AL AHMED'
  UNION ALL SELECT 'SBS', 'SABAH AL SALEM'
  UNION ALL SELECT 'SAL', 'SALMIYA'
  UNION ALL SELECT 'SLW', 'SALWA'
  UNION ALL SELECT 'SMY', 'SHAMIYA'
  UNION ALL SELECT 'SHD', 'SHUHADA'
  UNION ALL SELECT 'VIB', 'VIBES'
  UNION ALL SELECT 'WAM', 'WEST ABDULLAH AL MUBARAK'
  UNION ALL SELECT 'YRD', 'YARD'
  UNION ALL SELECT 'ZAH', 'ZAHRA'
) source
ON target.LOCATION_CODE = source.LOCATION_CODE
WHEN MATCHED THEN UPDATE SET target.LOCATION_NAME = source.LOCATION_NAME
WHEN NOT MATCHED THEN INSERT (LOCATION_CODE, LOCATION_NAME) VALUES (source.LOCATION_CODE, source.LOCATION_NAME);
