USE DATABASE SWISH_DOCUMENTS;
USE SCHEMA ECS_MVP;

CREATE OR REPLACE TABLE LOCATIONS (
  LOCATION_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1,
  LOCATION_CODE VARCHAR(50) NOT NULL,
  LOCATION_NAME VARCHAR(200) NOT NULL,
  IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_TZ,
  PRIMARY KEY (LOCATION_ID)
);

CREATE OR REPLACE TABLE BRAND_LOCATIONS (
  BRAND_LOCATION_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1,
  BRAND_ID NUMBER(38,0) NOT NULL,
  LOCATION_ID NUMBER(38,0) NOT NULL,
  IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_TZ,
  PRIMARY KEY (BRAND_LOCATION_ID)
);

ALTER TABLE LOCATIONS ADD CONSTRAINT UQ_LOCATIONS_LOCATION_CODE UNIQUE (LOCATION_CODE);
ALTER TABLE BRAND_LOCATIONS ADD CONSTRAINT UQ_BRAND_LOCATIONS UNIQUE (BRAND_ID, LOCATION_ID);

ALTER TABLE USERS ADD COLUMN IF NOT EXISTS LOCATION_ID NUMBER(38,0);

ALTER TABLE SOPS ADD COLUMN IF NOT EXISTS LOCATION_ID NUMBER(38,0);
ALTER TABLE SOPS ALTER COLUMN DEPARTMENT_ID DROP NOT NULL;

ALTER TABLE SOP_ASSIGNMENTS ADD COLUMN IF NOT EXISTS LOCATION_ID NUMBER(38,0);
ALTER TABLE SOP_ASSIGNMENTS ALTER COLUMN DEPARTMENT_ID DROP NOT NULL;

ALTER TABLE AUDITS ADD COLUMN IF NOT EXISTS LOCATION_ID NUMBER(38,0);
ALTER TABLE AUDITS ALTER COLUMN DEPARTMENT_ID DROP NOT NULL;

ALTER TABLE CORRECTIVE_ACTIONS ADD COLUMN IF NOT EXISTS LOCATION_ID NUMBER(38,0);

ALTER TABLE KPI_DEFINITIONS ADD COLUMN IF NOT EXISTS LOCATION_ID NUMBER(38,0);
ALTER TABLE KPI_RESULTS ADD COLUMN IF NOT EXISTS BRAND_ID NUMBER(38,0);
ALTER TABLE KPI_RESULTS ADD COLUMN IF NOT EXISTS DEPARTMENT_ID NUMBER(38,0);
ALTER TABLE KPI_RESULTS ADD COLUMN IF NOT EXISTS LOCATION_ID NUMBER(38,0);
