USE DATABASE SWISH_DOCUMENTS;
USE SCHEMA ECS_MVP;

ALTER TABLE SOPS ADD COLUMN IF NOT EXISTS STORAGE_PROVIDER VARCHAR(30);
ALTER TABLE SOPS ADD COLUMN IF NOT EXISTS STORAGE_DRIVE_ID VARCHAR(255);
ALTER TABLE SOPS ADD COLUMN IF NOT EXISTS STORAGE_ITEM_ID VARCHAR(255);
ALTER TABLE SOPS ADD COLUMN IF NOT EXISTS STORAGE_PATH VARCHAR(1000);

ALTER TABLE EVIDENCE_FILES ADD COLUMN IF NOT EXISTS STORAGE_PROVIDER VARCHAR(30);
ALTER TABLE EVIDENCE_FILES ADD COLUMN IF NOT EXISTS STORAGE_DRIVE_ID VARCHAR(255);
ALTER TABLE EVIDENCE_FILES ADD COLUMN IF NOT EXISTS STORAGE_ITEM_ID VARCHAR(255);
ALTER TABLE EVIDENCE_FILES ADD COLUMN IF NOT EXISTS STORAGE_PATH VARCHAR(1000);

CREATE OR REPLACE TABLE FILE_ACCESS_RULES (
  RULE_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1,
  ENTITY_TYPE VARCHAR(50) NOT NULL,
  ENTITY_ID NUMBER(38,0) NOT NULL,
  ROLE_ID NUMBER(38,0),
  USER_ID NUMBER(38,0),
  BRAND_ID NUMBER(38,0),
  DEPARTMENT_ID NUMBER(38,0),
  LOCATION_ID NUMBER(38,0),
  CAN_VIEW BOOLEAN NOT NULL DEFAULT TRUE,
  CAN_DOWNLOAD BOOLEAN NOT NULL DEFAULT TRUE,
  CAN_EDIT BOOLEAN NOT NULL DEFAULT FALSE,
  CREATED_BY NUMBER(38,0) NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (RULE_ID)
);
