-- Multi-scope user access foundation.
-- Keeps existing USERS.BRAND_ID / DEPARTMENT_ID / LOCATION_ID as default values
-- while introducing many-to-many scope membership and explicit "all" access flags.

ALTER TABLE USERS ADD COLUMN IF NOT EXISTS HAS_ALL_BRANDS BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE USERS ADD COLUMN IF NOT EXISTS HAS_ALL_DEPARTMENTS BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE USERS ADD COLUMN IF NOT EXISTS HAS_ALL_LOCATIONS BOOLEAN NOT NULL DEFAULT FALSE;

CREATE OR REPLACE TABLE USER_BRANDS (
  USER_ID NUMBER(38,0) NOT NULL,
  BRAND_ID NUMBER(38,0) NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (USER_ID, BRAND_ID)
);

CREATE OR REPLACE TABLE USER_DEPARTMENTS (
  USER_ID NUMBER(38,0) NOT NULL,
  DEPARTMENT_ID NUMBER(38,0) NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (USER_ID, DEPARTMENT_ID)
);

CREATE OR REPLACE TABLE USER_LOCATIONS (
  USER_ID NUMBER(38,0) NOT NULL,
  LOCATION_ID NUMBER(38,0) NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (USER_ID, LOCATION_ID)
);

INSERT INTO USER_BRANDS (USER_ID, BRAND_ID)
SELECT USER_ID, BRAND_ID
FROM USERS
WHERE BRAND_ID IS NOT NULL
  AND NOT EXISTS (
    SELECT 1
    FROM USER_BRANDS ub
    WHERE ub.USER_ID = USERS.USER_ID
      AND ub.BRAND_ID = USERS.BRAND_ID
  );

INSERT INTO USER_DEPARTMENTS (USER_ID, DEPARTMENT_ID)
SELECT USER_ID, DEPARTMENT_ID
FROM USERS
WHERE DEPARTMENT_ID IS NOT NULL
  AND NOT EXISTS (
    SELECT 1
    FROM USER_DEPARTMENTS ud
    WHERE ud.USER_ID = USERS.USER_ID
      AND ud.DEPARTMENT_ID = USERS.DEPARTMENT_ID
  );

INSERT INTO USER_LOCATIONS (USER_ID, LOCATION_ID)
SELECT USER_ID, LOCATION_ID
FROM USERS
WHERE LOCATION_ID IS NOT NULL
  AND NOT EXISTS (
    SELECT 1
    FROM USER_LOCATIONS ul
    WHERE ul.USER_ID = USERS.USER_ID
      AND ul.LOCATION_ID = USERS.LOCATION_ID
  );